### ISSUE TITLE
タグ打ち

### ISSUE THREAD

**Issue by sksat** [sksat/papermc-docker#8]
Renovateでやりたいので．PRがマージされたらタグ打つのってできるのかな．

**Comment by sksat** [comment]
できたとしてタグに紐付いたイメージが必要なのでpersonal access token生やしてやらないといけない

**Comment by sksat** [comment]
```
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  job:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
```
でいけるらしい
